### ISSUE TITLE
secrets.json file not opened

### ISSUE THREAD

**Issue by JaMatus** [Reptarsrage/vscode-manage-user-secrets#14]
menu option does not open up the secrets.json file for editing.

**Comment by Reptarsrage** [comment]
So I noticed that if the User Secrets directory doesn't exist `mkdir` is failing to create the path. Hopefully I've addressed this issue in v`1.0.2`. Please let me know once you upgrade if you're still getting this error. 

A temporary fix would be to create one of the following directories:
Windows: `%APPDATA%\Microsoft\UserSecrets\<user_secrets_id>`
Mac/Linux: `~/.microsoft/usersecrets/<user_secrets_id>`
